<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <Authors>Alexander Shabunevich</Authors>
    <Copyright>Copyright © 2018 Alexander Shabunevich</Copyright>
    <PackageProjectUrl>https://github.com/Iamcerba/HttpClient.Extensions.LoggingHttpMessageHandler</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Iamcerba/HttpClient.Extensions.LoggingHttpMessageHandler</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <PackageTags>systemnethttp, http, httpclient, logging, messagehandler, delegatinghandler</PackageTags>
    <Description>Provides a message handler for HttpClient which allows to enable logging of request/response related info. In comparison with Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler it allows to log request/response content.</Description>
    <PackageId>HttpClient.Extensions.LoggingHttpMessageHandler</PackageId>
    <Version>1.0.4</Version>
    <AssemblyVersion>1.0.4.0</AssemblyVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>

</Project>
